spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Test
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jps:
    generate-ddl: true
    hibernate:
      dll-auto: create
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

